#table creation

create table USERS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
USERNAME VARCHAR(255) NOT NULL,
MAILID VARCHAR(255) NOT NULL,
MOBILENO VARCHAR(255) NOT NULL,
GENDER VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL
);


create table STUDENT(
ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
MAILID VARCHAR(255) NOT NULL,
BRANCH VARCHAR(255) NOT NULL,
BIRTHDATE VARCHAR(255) NOT NULL,
GENDER VARCHAR(255) NOT NULL
);
